### ISSUE TITLE
TS2694: Express.Multer.File not found in candidate.controller.ts

### ISSUE THREAD

**Issue by sberoch** [sberoch/hiringpeak#13]
> *This was generated by AI during triage.*

Parent PRD: #10. Regression introduced by #11 (PDF intake flow).

## Error

```
apps/api/src/candidate/candidate.controller.ts:56:48 - error TS2694: Namespace 'global.Express' has no exported member 'Multer'.

56   async parsePdf(@UploadedFile() file: Express.Multer.File) {
                                                  ~~~~~~
```

## Likely cause

`@types/multer` is pinned at `^2.1.0` in `apps/api/package.json`. The v2 release no longer augments the global `Express` namespace the way v1 did, so `Express.Multer.File` no longer resolves.

Common fixes:
- Import the type from `multer` directly (`import type { Multer } from 'multer'`, then use `Multer.File`).
- Or pin `@types/multer` to `^1`.

## Repro

Run the API typechecker:
```
pnpm --filter @workspace/api typecheck
```

## Affected file

- `apps/api/src/candidate/candidate.controller.ts:56`

**Comment by sberoch** [comment]
Fixed via merge of `sandcastle/issue-13-fix-multer-type` into main.
